# Based on https://docs.haskellstack.org/en/stable/travis_ci/

sudo: false

language: generic

os:
  - osx
  - linux

# GHC versions prior to 7.10.3 are not supported.
#
# Based on "Latest (stack) LTS per GHC version" (https://www.stackage.org/)
env:
  - RESOLVER="lts-6.35"         # ghc 7.10.3
  - RESOLVER="lts-9.21"         # ghc 8.0.2
  - RESOLVER="lts-11.20"        # ghc 8.2.2
  - RESOLVER="lts-12.5"         # ghc 8.4.3
  - RESOLVER="lts-16.2" .       # ghc 8.8.3
  - RESOLVER="nightly"

matrix:
  allow_failures:
    - env: RESOLVER="nightly"

cache:
  directories:
  - $HOME/.stack
  timeout: 1800


addons:
  apt:
    packages:
    - libasound2-dev

before_install:

- set -ex
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
- set +ex

script:
- set -ex
- stack --no-terminal --resolver $RESOLVER build --install-ghc --only-dependencies -j2
- stack --no-terminal --resolver $RESOLVER test --pedantic --haddock --no-haddock-deps -j2
- set +ex
